
reference_variables:

  EDGAR AR6:
    ref_year: 2019
    compare_year: 2019
    model: Reference
    scenario: EDGAR AR6
    key_historical: True
    key_future: False
    variables_threshold:
      # Emissions|CO2: 0.4
      Emissions|CO2|Energy and Industrial Processes: 0.2
      Emissions|CO2|Energy: 0.2
      Emissions|CH4: 0.4
      # Emissions|N2O: 0.4    
    missing_flags:
      # Emissions|CO2: Fail
      Emissions|CO2|Energy and Industrial Processes: Fail_missing
      Emissions|CO2|Energy: Fail_missing
      Emissions|CH4: Pass_missing
      # Emissions|N2O: Pass         


  IEA Primary Energy:
    ref_year: 2019
    compare_year: 2019
    model: Reference
    scenario: IEA Energy Statistics (r2022)
    key_historical: True
    key_future: False
    variables_threshold:
      Primary Energy: 0.2
      Primary Energy|Nuclear: 0.3
    missing_flags:
      Primary Energy: Fail_missing
      Primary Energy|Nuclear: Pass_missing      

  IEA Electricity:
    ref_year: 2019
    compare_year: 2019
    model: Reference
    scenario: IEA Energy Statistics (r2022)
    key_historical: False
    key_future: False
    variables_threshold:
      Secondary Energy|Electricity: 0.3
      Secondary Energy|Electricity|Nuclear: 0.3
      # Secondary Energy|Electricity|Solar-Wind: 0.5
    missing_flags:
      Secondary Energy|Electricity: Fail_missing
      Secondary Energy|Electricity|Nuclear: Pass_missing
      # Secondary Energy|Electricity|Solar-Wind: Pass_missing       
      
  Solar-Wind2020:
    ref_year: 2020
    compare_year: 2020
    model: Reference
    scenario: Solar-Wind-composite
    key_historical: True
    key_future: False
    variables_threshold:
      Secondary Energy|Electricity|Solar-Wind: 0.5
    missing_flags:
      Secondary Energy|Electricity|Solar-Wind: Pass_missing

    

aggregation_variables:
  # CO2:
    # variable: Emissions|CO2
    # threshold: 0.2
    # key_historical: False
    # key_future: False
  CCS:
    variable: Carbon Sequestration|CCS
    threshold: 0.2
    key_historical: False
    key_future: False
  Primary Energy:
    variable: Primary Energy
    threshold: 0.2
    key_historical: False
    key_future: False    

bounds_variables:

# Key recent emissions

# (these are included above)
  # EDGAR Emissions|CO2 2019:
    # variable: Emissions|CO2
    # lo: 44251
    # up: 44251.1
    # year: 2019
    # key_historical: True
    # key_future: False
    # bound_threshold: 0.4
    
  # EDGAR Emissions|CO2|EIP:
    # variable: Emissions|CO2|Energy and Industrial Processes
    # lo: 37646
    # up: 37646.1
    # year: 2019
    # key_historical: True
    # key_future: False
    # bound_threshold: 0.2

  # EDGAR Emissions|CH4 2019:
    # variable: Emissions|CH4
    # lo: 379.24
    # up: 379.241
    # year: 2019
    # key_historical: True
    # key_future: False
    # bound_threshold: 0.4

  Emissions|CO2|Energy and Industrial Processes factor % change '15-'20:
    variable: Emissions|CO2|Energy and Industrial Processes|2015-2020 change
    lo: 0
    up: 20
    year: 2015
    key_historical: True
    key_future: False
    missing_flag: Fail_missing
    bound_threshold: 1
    description:  Permitted range of % change in Emissions CO2 EIP

  Emissions|CO2|Energy factor % change '15-'20:
    variable: Emissions|CO2|Energy|2015-2020 change
    lo: -2.5
    up: 20
    year: 2015
    key_historical: True
    key_future: False
    missing_flag: Fail_missing    
    bound_threshold: 1
    description:  Permitted range of % change in Emissions CO2 Energy


# Key near-term feasibility checks
    
  No net negative EIP before 2030:
    variable: Emissions|CO2|Energy and Industrial Processes
    lo: 0
    up: 80000
    year: 2010-2030
    key_historical: False
    key_future: True
    missing_flag: Pass_missing    
    bound_threshold: 1
    
  No net negative Energy before 2030:
    variable: Emissions|CO2|Energy
    lo: 0
    up: 60000
    year: 2010-2030
    key_historical: False
    key_future: True
    missing_flag: Pass_missing    
    bound_threshold: 1

  CCS from Energy 2020:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: 0
    up: 250
    year: 2020
    key_historical: True
    key_future: False
    missing_flag: Pass_missing    
    bound_threshold: 1 
    description:  Permitted range of CO2 capture from Energy sector

  CCS from Energy 2030:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: 0
    up: 2000
    year: 2030
    key_historical: False
    key_future: True
    missing_flag: Pass_missing    
    bound_threshold: 1
    
  Electricity from Nuclear in 2030:
    variable: Secondary Energy|Electricity|Nuclear
    lo: 0
    up: 20
    year: 2030
    key_historical: False
    key_future: True
    missing_flag: Pass_missing    
    bound_threshold: 1
  
  # Secondary Energy Solar-Wind factor x change '20-'30:
    # variable: Secondary Energy|Electricity|Solar-Wind|2020-2030 change
    # lo: 0
    # up: 20
    # year: 2020
    # key_historical: False
    # key_future: True
    # bound_threshold: 1
    # description:  Permitted range of  factor x change in Wind+Solar electricity
