- PROMETHEUS 1.2:
  - PROMETHEUS 1.2|Western Europe:
      iso3_codes: [AUT, BEL, DNK, FRO, FIN, FRA, DEU, GIB, GRC, ISL, IRL, IMN, ITA,
        LIE, LUX, MCO, NLD, NOR, PRT, SMR, ESP, SWE, CHE, GBR]
  - PROMETHEUS 1.2|Central Europe:
      iso3_codes: [BGR, HRV, CYP, CZE, EST, HUN, LVA, LTU, MLT, POL, ROU, SVK, SVN]
